const API="https://efyyanjbgbpaohvkezes.supabase.co/functions/v1/workout-api";
const state={token:"",data:null,program:"emphasis",workout:"A",drafts:{},identities:{}};
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")};
function tokenFromUrl(){return WorkoutAccess.tokenFromUrl()}
async function call(action,opt={}){const res=await fetch(API+"?action="+encodeURIComponent(action),{...opt,headers:{"Content-Type":"application/json","x-workout-key":state.token,...(opt.headers||{})}});const d=await res.json().catch(()=>({}));if(!res.ok)throw new Error(d.error||"הפעולה נכשלה");return d}
function uuid(){return crypto.randomUUID()}
function currentKey(){return state.program+"-"+state.workout}
// Each user/date/program/workout has its own save identity. Never reuse a saved session across workouts.
function sessionContext(){return [state.data.user.user_key,state.program,state.workout,$('#date').value||today()].join('|')}
function sessionIdentity(){const key=sessionContext();return state.identities[key]||(state.identities[key]={id:uuid(),revision:0})}
function stash(){if(!state.data)return;state.drafts[currentKey()]=collect(true)}
function restore(){const d=state.drafts[currentKey()];if(!d)return;$("#date").value=d.performed_at||today();$("#duration").value=d.duration_minutes||"";$("#sessionNotes").value=d.notes||"";for(const ex of d.exercises||[]){const card=document.querySelector('[data-slot="'+CSS.escape(ex.slot_id)+'"]');if(!card)continue;card.querySelector(".exercise-note").value=ex.exercise_note||"";const box=card.querySelector(".sets");box.innerHTML="";(ex.sets||[]).forEach((s,i)=>box.insertAdjacentHTML("beforeend",setRow(i+1,card.dataset.metric,s)))}}
function previous(slot,key){const sessions=state.data.history||[];for(const s of sessions){const rows=(s.sets||[]).filter(x=>(x.slot_id||x.exercise_key)===slot||x.exercise_key===key);if(rows.length)return{s,rows}}return null}
function prevHtml(e){const p=previous(e.exercise_key,e.exercise_key);if(!p)return '<div class="previous muted">אין עדיין ביצוע קודם לתרגיל הזה.</div>';const lines=p.rows.slice().sort((a,b)=>a.set_number-b.set_number).map(x=>{const bits=[];if(x.load_text)bits.push(x.load_text);if(x.reps_text)bits.push(x.reps_text+" חזרות");if(x.duration_seconds)bits.push(x.duration_seconds+" שנ׳");if(x.rir_text)bits.push("RIR "+x.rir_text);if(x.notes)bits.push(x.notes);return esc("סט "+x.set_number+": "+bits.join(" · "))}).join("<br>");const note=p.s.exercise_notes?.[e.exercise_key];return '<div class="previous"><strong>בפעם הקודמת — '+esc(p.s.performed_at)+'</strong>'+lines+(note?'<br>'+esc(note):'')+"</div>"}
function metricLabel(m){if(m==="seconds_per_side")return "שניות לכל צד";if(m==="reps_per_side")return "חזרות לכל צד";return m==="seconds"?"שניות":"חזרות"}
function setRow(n,metric,v={}){const timed=metric==="seconds"||metric==="seconds_per_side";return '<div class="setrow"><span class="setnum">'+n+'</span><input class="load" placeholder="משקל / סיוע" value="'+esc(v.load_text||"")+'"><input class="metric" inputmode="decimal" placeholder="'+metricLabel(metric)+'" value="'+esc(timed?(v.duration_seconds||""):(v.reps_text||""))+'"><input class="rir" placeholder="2 / קשה / כמעט כשל" value="'+esc(v.rir_text||"")+'"></div>'}
function card(e){let rows="";for(let i=1;i<=Number(e.planned_sets||2);i++)rows+=setRow(i,e.metric_type);return '<section class="card exercise" data-slot="'+esc(e.exercise_key)+'" data-key="'+esc(e.exercise_key)+'" data-name="'+esc(e.exercise_name)+'" data-metric="'+esc(e.metric_type)+'"><div class="head"><div><h3>'+esc(e.exercise_name)+'</h3><div class="meta">'+esc(e.planned_sets)+" סטים · "+esc(e.rep_time_range)+(e.target_rir?" · RIR יעד "+esc(e.target_rir):"")+(e.rest_superset?"<br>"+esc(e.rest_superset):"")+(e.coaching_notes?"<br>"+esc(e.coaching_notes):"")+'</div></div><a class="demo" target="_blank" rel="noopener noreferrer" href="'+esc(e.demo_url||"#")+'">הדגמה ↗</a></div>'+prevHtml(e)+'<div class="labels"><span>סט</span><span>'+esc(e.load_label||"משקל / סיוע")+'</span><span>'+metricLabel(e.metric_type)+'</span><span>RIR / קושי</span></div><div class="sets">'+rows+'</div><button class="small add" type="button">+ סט</button><textarea class="exercise-note" placeholder="הערה לתרגיל — אופציונלי"></textarea></section>'}
function render(){if(!state.data)return;document.querySelectorAll("[data-program]").forEach(b=>b.classList.toggle("active",b.dataset.program===state.program));const avail=[...new Set(state.data.programs.filter(x=>x.program_key===state.program).map(x=>x.workout_code))];if(!avail.includes(state.workout))state.workout=avail[0]||"A";$("#tabs").innerHTML=["A","B","C","D"].filter(x=>avail.includes(x)).map(x=>'<button data-w="'+x+'" class="'+(x===state.workout?"active":"")+'">'+x+(x==="D"?" · אופציונלי":"")+"</button>").join("");$("#tabs").querySelectorAll("button").forEach(b=>b.onclick=()=>{stash();state.workout=b.dataset.w;render()});const ex=state.data.programs.filter(x=>x.program_key===state.program&&x.workout_code===state.workout).sort((a,b)=>a.exercise_order-b.exercise_order),main=ex.filter(x=>x.section==="main"),bonus=ex.filter(x=>x.section==="bonus");$("#list").innerHTML=main.map(card).join("")+(bonus.length?'<div class="bonus">אם נשאר זמן ויש כוח</div>'+bonus.map(card).join(""):"");document.querySelectorAll(".add").forEach(b=>b.onclick=()=>{const c=b.closest(".exercise"),box=c.querySelector(".sets");if(box.children.length<20)box.insertAdjacentHTML("beforeend",setRow(box.children.length+1,c.dataset.metric))});$("#duration").value="";$("#sessionNotes").value="";$("#status").textContent="";$("#notice").classList.add("hidden");$("#finish").classList.remove("hidden");$("#savebar").classList.remove("hidden");restore()}
function collect(keepEmpty=false){const exercises=[];document.querySelectorAll(".exercise").forEach(c=>{const metric=c.dataset.metric||"reps",note=c.querySelector(".exercise-note").value.trim(),sets=[];c.querySelectorAll(".setrow").forEach((r,i)=>{const load=r.querySelector(".load").value.trim(),val=r.querySelector(".metric").value.trim(),rir=r.querySelector(".rir").value.trim();if(keepEmpty||load||val||rir)sets.push({set_number:i+1,load_text:load,reps_text:metric.startsWith("reps")?val:"",duration_seconds:metric.startsWith("seconds")?val:"",rir_text:rir,notes:""})});if(keepEmpty||sets.length||note)exercises.push({slot_id:c.dataset.slot,exercise_key:c.dataset.key,exercise_name:c.dataset.name,variant_label:"",exercise_note:note,sets})});const identity=sessionIdentity();return{id:identity.id,revision:identity.revision,program_key:state.program,workout_code:state.workout,performed_at:$("#date").value||today(),duration_minutes:$("#duration").value.trim(),notes:$("#sessionNotes").value.trim(),exercises}}
async function boot(){state.token=tokenFromUrl();$("#date").value=today();if(!state.token){$("#notice").classList.add("error");$("#notice").textContent="חסר קישור גישה אישי. פתחי את הקישור שקיבלת לאפליקציה.";return}try{state.data=await call("bootstrap");$("#who").textContent=state.data.user.display_name;WorkoutAccess.showLinkTools(state.token);state.program=localStorage.getItem("workoutProgram")||state.data.user.default_program||"emphasis";if(state.data.is_owner)$("#ownerTools").classList.remove("hidden");document.querySelectorAll("[data-program]").forEach(b=>b.onclick=()=>{stash();state.program=b.dataset.program;localStorage.setItem("workoutProgram",state.program);state.workout="A";render()});render()}catch(e){$("#notice").classList.add("error");$("#notice").textContent=e.message}}
$("#saveBtn").onclick=async()=>{const b=$("#saveBtn"),s=$("#status"),payload=collect(),identity=sessionIdentity();const nav=[...document.querySelectorAll(".top button,.top input")];b.disabled=true;nav.forEach(x=>x.disabled=true);s.className="";s.textContent="שומרת…";try{const d=await call("save",{method:"POST",body:JSON.stringify(payload)});identity.revision=d.revision??identity.revision;state.drafts[currentKey()]=collect(true);s.className="saved";s.textContent="האימון נשמר ✓";try{const h=await call("history");state.data.history=h.history||[]}catch(_){s.textContent="האימון נשמר ✓ — רענון ההיסטוריה לא הצליח כרגע"}}catch(e){s.className="bad";s.textContent=e.message}finally{b.disabled=false;nav.forEach(x=>x.disabled=false)}};
$("#guestBtn").onclick=async()=>{const b=$("#guestBtn");if(b.disabled)return;const name=prompt("שם המשתמשת החדשה:");if(!name||!name.trim())return;b.disabled=true;try{const d=await call("create_guest",{method:"POST",body:JSON.stringify({display_name:name.trim()})});if(!d.ok||!d.token)throw new Error("לא התקבל קישור תקין.");const link=WorkoutAccess.linkFor(d.token);try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(link)}catch(_){}prompt("הקישור האישי נוצר. העתיקי ושלחי אותו למשתמשת. אל תשתפי את הקישור האישי שלך:",link)}catch(e){alert(e.message)}finally{b.disabled=false}};
boot();
